spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/camp-reservation
    username: postgres
    password: postgres
  messages:
    basename: messages, ValidationMessages

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.example.demo.domain.model
